export const PROCESS_STORE_OPS = [
  'getJob',
  'saveJob',
  'listJobs',
  'hasTrainingInFlight',
  'setTrainingInFlight',
  'clearTrainingInFlight',
  'getIdempotency',
  'saveIdempotency',
  'getProfile',
  'saveProfile',
  'getEnumExtras',
  'addEnumExtra',
  'listProfiles',
  'deleteProfile',
  'getVersionLabel',
  'setVersionLabel',
  'getActiveVersionId',
  'setActiveVersionId',
  'appendActivation',
  'wasActivated',
  'getQuarantine',
  'appendQuarantine',
  'markSyntheticIndex',
  'markSyntheticSource',
  'appendPublishedIds',
  'getPublishedIds',
  'saveDraftDocuments',
  'getDraftDocuments',
  'listDocumentTypes',
  'hasDocumentType',
  'addDocumentType',
  'deleteDocumentType',
] as const;

export type ProcessStoreOp = (typeof PROCESS_STORE_OPS)[number];
